name: maybe-thibran
version: '0.5.0'
summary: jump to known folder on the command-line
description: |
  Shell configuration (bash, fish, eshell) & How-To:
    github.com/thibran/maybe
grade:       stable
confinement: strict

apps:
  maybe:
    command: bin/maybe
    plugs: [home]

parts:
  go:
    source-tag: go1.10
  maybe:
    after: [go]
    plugin: go
    source: .
    go-importpath: github.com/thibran/maybe
    install: |
      strip --strip-all $SNAPCRAFT_PART_INSTALL/bin/maybe
